const PLAYLIST_DATA = [
    { title: "Cryptopiano - Bright Horizons", videoId: "IhDQzo4DHGg" },
    { title: "Cryptopiano - The Light Around the Bend", videoId: "vpUP9DnA-O0" },
    { title: "Cryptopiano - Mind Reset", videoId: "0mhHEEyLDXo" },
    { title: "Cryptopiano - Rise in the Glow", videoId: "-UYlUQHeIts" },
    { title: "Cryptopiano - Fight to Breathe", videoId: "pbBue2otqic" },
    { title: "Cryptopiano - Empty Hands", videoId: "cAkhWH1AGVc" },
    { title: "Cryptopiano - Tired of It All", videoId: "bEVSBGK7Cjw" },
    { title: "Cryptopiano - Shattered Blueprint", videoId: "2r2VmnDinKs" },
    { title: "Cryptopiano - Black Belt for the Brave", videoId: "Ggib8zDtjoc" },
    { title: "Cryptopiano - Shimmering Blue", videoId: "2Us-0eP2re4" },
    { title: "Cryptopiano - Strolling All Along Jam", videoId: "WkyziVjsQUk" },
    { title: "Cryptopiano - Pichoune Swing", videoId: "-KX7VYgoUUs" },
    { title: "Cryptopiano - Flickering Flame", videoId: "lRQO2vYCxMc" },
    { title: "Cryptopiano - Forgotten Footprints", videoId: "YckjrP71aTI" },
    { title: "Cryptopiano - Shadows of You", videoId: "cjCCPnxScjY" },
    { title: "Cryptopiano - Can't Stop Dreaming", videoId: "xNd52jXFdSA" },
    { title: "Cryptopiano - Where Did The Love Go", videoId: "Ot71sgl_lqg" },
    { title: "Cryptopiano - Shattered Souls", videoId: "pGANKfP843Q" },
    { title: "Cryptopiano - Shady Side Blues", videoId: "N6kF-M4qcXY" },
    { title: "Cryptopiano - Daylight Break", videoId: "HZGX9c1GJWw" },
    { title: "Cryptopiano - Golden Cross", videoId: "97JmsjgPhvc" },
    { title: "Cryptopiano - In This Frame", videoId: "5oBqIa9S-zA" },
    { title: "Cryptopiano - Pulsing Through the Echoes", videoId: "D9NnjcUSyQ4" },
    { title: "Cryptopiano - Magic Earth", videoId: "2VgCCOpiN74" },
    { title: "Cryptopiano - Break The Lines", videoId: "2ikx_D0ZRbw" },
    { title: "Cryptopiano - Out of Orbit", videoId: "JuqYAIoGlNE" },
    { title: "Cryptopiano - Lonely to Looney", videoId: "L5lWIBrTvWE" },
    { title: "Cryptopiano - No More Lies", videoId: "tT58iLrE7iQ" },
    { title: "Cryptopiano - Behind the Walls", videoId: "dtBAb8iJrLA" },
    { title: "Cryptopiano - Give Me A New Beat", videoId: "KuMGtuVjm8w" },
    { title: "Cryptopiano - I Want Only Light", videoId: "KEEegKBgRbs" },
    { title: "Cryptopiano - The Same Old, The Same Old", videoId: "e3mcr-nmmB0" },
    { title: "Cryptopiano - Feel Good Again", videoId: "_7cvIqWWWGE" },
    { title: "Cryptopiano - No Place to Escape", videoId: "MK2fhnAriUk" },
    { title: "Cryptopiano - Prison of Me", videoId: "Ds5heN0ywi0" },
    { title: "Cryptopiano - Wild Kingdom", videoId: "Nxl2mfRh484" },
    { title: "Cryptopiano - The Beast Within", videoId: "VRMaP2PiRZ4" },
    { title: "Cryptopiano - The Jungle Bazaar", videoId: "d65mDCLOWas" },
    { title: "Cryptopiano - A Jungle Beast", videoId: "PH5Aj78mFtk" },
    { title: "Cryptopiano - Jungle Fever", videoId: "GiLGPYSs3Is" },
    { title: "Cryptopiano - Hot Jungle Love", videoId: "scdEYziRYtg" },
    { title: "Cryptopiano - Scary Jungle Nights", videoId: "DJzDq9OAGnM" },
    { title: "Cryptopiano - Mystic Whispers", videoId: "eoyBf6i8VGw" },
    { title: "Cryptopiano - An Ancient Jungle Tale", videoId: "vro7gOlVgDs" },
    { title: "Cryptopiano - Freedom in the Jungle", videoId: "pBk41PamHK4" },
    { title: "Cryptopiano - Elephant, King of the Jungle", videoId: "cRd36BJ2n78" },
    { title: "Cryptopiano - Herd of Beasts", videoId: "aandLRX5PJo" },
    { title: "Cryptopiano - My Camel Sings", videoId: "2ctye42zaSI" },
    { title: "Cryptopiano - Danger in the Jungle Lake", videoId: "0AedTcWZEtE" },
    { title: "Cryptopiano - Tiger's Tale", videoId: "8zN7h_-tjY8" },
    { title: "Cryptopiano - Jungle Fever Dream", videoId: "fE8whHIs0Ww" },
    { title: "Cryptopiano - Fight for Territory", videoId: "YBshDBurnH4" },
    { title: "Cryptopiano - Run With The Wind", videoId: "ICT99K1E7I4" },
    { title: "Cryptopiano - Screams of the Wild", videoId: "PdcpFLvZHaw" },
    { title: "Cryptopiano - Secrets in the Deep Jungle", videoId: "rXT3kxtKAcM" },
    { title: "Cryptopiano - Crazy Safari", videoId: "_OW1SH_SyPg" },
    { title: "Cryptopiano - Jungle Heartbeat", videoId: "Xqj3kilR06k" },
    { title: "Cryptopiano - The Jungle Breathes", videoId: "XmDs1oTpP0Y" },
    { title: "Cryptopiano - Wild Safari", videoId: "qT7hxXWAZ-4" },
    { title: "Cryptopiano - Long Path in Front", videoId: "jg_kLvszpJs" },
    { title: "Cryptopiano - Attached to the Stars", videoId: "d2sqfQlQg8U" },
    { title: "Cryptopiano - Through the Canopy", videoId: "D9nT8hSaPHM" },
    { title: "Cryptopiano - The Jungle Speaks", videoId: "7W9lgqU4Fsk" },
    { title: "Cryptopiano - Feel The Ground", videoId: "_d-sh9Rg5d8" },
    { title: "Cryptopiano - Hunted Shadows (Symphonic Interlude)", videoId: "ZM40U879cqI" },
    { title: "Cryptopiano - Dance So the Souls", videoId: "YbY2wEToxzA" },
    { title: "Cryptopiano - Tribal Echoes", videoId: "nk9Hx_n7iLg" },
    { title: "Cryptopiano - Tiger in the Mist", videoId: "gst3eO0mN0Q" },
    { title: "Cryptopiano - Survival's Code", videoId: "x7-K4L8AvvA" },
    { title: "Cryptopiano - Lost in the Wilds", videoId: "KuqbMe9bDik" },
    { title: "Cryptopiano - Whispers in the Canopy", videoId: "_Jq6QVBS45M" },
    { title: "Cryptopiano - Recall", videoId: "kt9VRURzfM8" },
    { title: "Cryptopiano - Whispers of Youth", videoId: "2lfW1UuWxZQ" },
    { title: "Cryptopiano - Evening Calm", videoId: "KbEyUAVzi0c" },
    { title: "Cryptopiano - Sunlit Dreams", videoId: "-7qwcSwxvOY" },
    { title: "Cryptopiano - Dancing Birds", videoId: "GdoW3tZljtY" },
    { title: "Cryptopiano - Sunflower Fields", videoId: "zef0YTBEA1Q" },
    { title: "Cryptopiano - Happy Jumping Goat", videoId: "SdyDZbQ1NaY" },
    { title: "Cryptopiano - Rabbit Hops", videoId: "Ec7c7hBCZSE" },
    { title: "Cryptopiano - Creek in My Woods", videoId: "FkU8idm9-fk" },
    { title: "Cryptopiano - Wheat in the Wind", videoId: "wRHlSpMcmUc" },
    { title: "Cryptopiano - Whispering Echoes", videoId: "vi9Za_UUI2M" },
    { title: "Cryptopiano - My Old Farm", videoId: "IfcaCWHHqsQ" },
    { title: "Cryptopiano - Whispers of the Ocean", videoId: "gD33YzGiLQY" },
    { title: "Cryptopiano - Hidden Ocean City", videoId: "_V4AHIC5NrA" },
    { title: "Cryptopiano - Where Ocean's Keep Their Secrets", videoId: "X2P2rBR8ew4" },
    { title: "Cryptopiano - Our Beach Rock", videoId: "ltbtClHIjfQ" },
    { title: "Cryptopiano - Starfish Story", videoId: "CGoK9yv2hdE" },
    { title: "Cryptopiano - Seagull's Serenade", videoId: "OHdC1mOY8Hw" },
    { title: "Cryptopiano - Whale's Serenade", videoId: "YDrgmLRhmh4" },
    { title: "Cryptopiano - Dolphin's Game", videoId: "e4QeI-_7j9U" },
    { title: "Cryptopiano - Turtle's Embrace", videoId: "3EfLmrmr7MI" },
    { title: "Cryptopiano - Pacific Serenity", videoId: "1If5cjN1RkQ" },
    { title: "Cryptopiano - Masters of Thought", videoId: "ULItxKyR5eY" },
    { title: "Cryptopiano - Far in the Future", videoId: "cc188aZL5BU" },
    { title: "Cryptopiano - Beyond the Speed of Light", videoId: "hKiV4aYLfho" },
    { title: "Cryptopiano - Whispers in the Dust", videoId: "l28ZytI1vkA" },
    { title: "Cryptopiano - Cosmic Checkmate", videoId: "GK3iGY-_Xwg" },
    { title: "Cryptopiano - Loving Minds", videoId: "xPmLPF67g44" },
    { title: "Cryptopiano - Unity in Motion", videoId: "G4hbkXJ1W58" },
    { title: "Cryptopiano - New Existence", videoId: "Drrqw6CeCbU" },
    { title: "Cryptopiano - On the Edge of Tomorrow", videoId: "mT_UWSgsCqo" },
    { title: "Cryptopiano - Vast Universe", videoId: "3buv5L7aEyk" },
    { title: "Cryptopiano - Aqua Sun (Happy Birthday Sis)", videoId: "GEbM1LUd5Fw" },
    { title: "Cryptopiano - Purple Wormhole", videoId: "k2CUZZbTJr0" },
    { title: "Cryptopiano - Meteors", videoId: "LPU1EKy-H0g" },
    { title: "Cryptopiano - Symbiotic Transformation", videoId: "2darF_bw1dE" },
    { title: "Cryptopiano - Progressive Thoughts", videoId: "7yLbtWlxwUE" },
    { title: "Cryptopiano - Blue Portal", videoId: "9a5B0NYxuHw" },
    { title: "Cryptopiano - Fata Morgana", videoId: "WhNvaXI5Oes" },
    { title: "Cryptopiano - Rock Valley", videoId: "qrbdfiU3zN4" },
    { title: "Cryptopiano - Silver Storm", videoId: "zepjvEYtLwc" },
    { title: "Cryptopiano - Mechanical Ghosts", videoId: "EkFuX-jqmpw" },
    { title: "Cryptopiano - Break Of A New Day", videoId: "YVEknnkKPAc" },
    { title: "Cryptopiano - Golden Horizon", videoId: "epKNBZjIWUM" },
    { title: "Cryptopiano - Facing the Sun", videoId: "Y19S8jUIXDU" },
    { title: "Cryptopiano - Dusty Day", videoId: "i5Aubm1WNBg" },
    { title: "Cryptopiano - Sunrise", videoId: "8B-lZmXI9v8" },
    { title: "Cryptopiano - High Above", videoId: "1vQ-IfC4Le4" },
    { title: "Cryptopiano - Blue Maze", videoId: "VmyzfYUKFpY" },
    { title: "Cryptopiano - Irregular Paths", videoId: "ZYZep2rgaNk" },
    { title: "Cryptopiano - Vast Blue", videoId: "MFzlubVaMZU" },
    { title: "Cryptopiano - Vast Distances", videoId: "NWzb3w1BaKc" },
    { title: "Cryptopiano - Unyielding Game", videoId: "LXfw_IOrUBw" },
    { title: "Cryptopiano - Unyielding Flame", videoId: "UTrQpA298Dg" },
    { title: "Cryptopiano - Day By Day", videoId: "_6tFoIWvEf4" },
    { title: "Cryptopiano - Today Changes", videoId: "ExPK9hyqT5I" },
    { title: "Cryptopiano - Blur", videoId: "uQVD5Z2vVp8" },
    { title: "Cryptopiano - Bring Back The Sun", videoId: "KEA9TrDudgM" },
    { title: "Cryptopiano - Sadness", videoId: "gxm7cF2rkvs" },
    { title: "Cryptopiano - Forgive The Fire", videoId: "8X1nB566lAA" },
    { title: "Cryptopiano - No Way Back", videoId: "T3OaZ1dxyVA" },
    { title: "Cryptopiano - Fading Scars", videoId: "lSlBB_vnxIU" },
    { title: "Cryptopiano - The Wandering Traveler", videoId: "d2Dm-9aAeuI" },
    { title: "Cryptopiano - Irregular Ways", videoId: "PRDCqvj5yzY" },
    { title: "Cryptopiano - Soul of Magicians", videoId: "mCapZKwdGAI" },
    { title: "Cryptopiano - Orbiting You", videoId: "iEBIFYYOclo" },
    { title: "Cryptopiano - Velvet Shadows of Enigma", videoId: "DeF3bq800MQ" },
    { title: "Cryptopiano - Beautiful Vision", videoId: "mc5A2Eq3K3g" },
    { title: "Cryptopiano - Cosmic Rainbow Love", videoId: "FUDQ9e96Ugg" },
    { title: "Cryptopiano - Take Me to Rainbow Galaxy", videoId: "ZhS_Y3pQ2S8" },
    { title: "Cryptopiano - I See You", videoId: "nIJKWlzv3BU" },
    { title: "Cryptopiano - Closer Than Ever", videoId: "TdeiYIE3z60" },
    { title: "Cryptopiano - We Float in Time Together", videoId: "VwQxmY3D7_s" },
    { title: "Cryptopiano - Missing You", videoId: "Da85895wT2Y" },
    { title: "Cryptopiano - Second Time Around", videoId: "W9bUFW5WU_I" },
    { title: "Cryptopiano - Chasing Shadows", videoId: "jPxwW4DR4mg" },
    { title: "Cryptopiano - Enigma's Echo", videoId: "oe2patwzYRg" },
    { title: "Cryptopiano - Timeless Drift", videoId: "P18WiFgXovo" },
    { title: "Cryptopiano - Floating to Infinity", videoId: "rkJ4k0q7UWM" },
    { title: "Cryptopiano - We Never Left", videoId: "2eMr9ofgjrY" },
    { title: "Cryptopiano - Love is Forever", videoId: "kRnV2Thl3dU" },
    { title: "Cryptopiano - Echoes of a Heartbeat", videoId: "SLzkT4AvGTQ" },
    { title: "Cryptopiano - Through Time and Stars", videoId: "Qt3ZSVd71Pk" },
    { title: "Cryptopiano - Mind's Mirage", videoId: "teX5xRRuC54" },
    { title: "Cryptopiano - Our Cosmic Dance", videoId: "J9145wGbsyc" },
    { title: "Cryptopiano - Floating to Infinite Skies (Duet)", videoId: "9ipcP3kPJbk" },
    { title: "Cryptopiano - Through the Dreamscapes (Duet)", videoId: "CAd1lkf4wkE" },
    { title: "Cryptopiano - Dreamscapes of You", videoId: "btQr-jXcR1s" },
    { title: "Cryptopiano - Dreamscapes and Echoes", videoId: "9muBojSgRpU" },
    { title: "Cryptopiano - Prism of Love", videoId: "QUxJnM7z32s" },
    { title: "Cryptopiano - Rainbow Dreamscapes", videoId: "Eprh1bLn8bw" },
    { title: "Cryptopiano - Space Noises (Augmented Remaster)", videoId: "S1exhnQZ-pA" },
    { title: "Cryptopiano - Galaxies Turning (Augmented Remaster)", videoId: "NfHnfc_B20s" },
    { title: "Cryptopiano - Fringe in Space (Augmented Remaster)", videoId: "jK4U9JARvwc" },
    { title: "Cryptopiano - Strange Planet (Augmented Remaster)", videoId: "iISbMomGBM8" },
    { title: "Cryptopiano - Two Minutes Left (Augmented Remaster)", videoId: "l_9oIl5lpWM" },
    { title: "Cryptopiano - Hiding On a Strange Planet (Augmented Remaster)", videoId: "dNFhAQL_Lb8" },
    { title: "Cryptopiano - Alien Attack (Augmented Remaster)", videoId: "vnisLTQPDs0" },
    { title: "Cryptopiano - Alien Chase (Augmented Remaster)", videoId: "GJDUmWRdmo4" },
    { title: "Cryptopiano - Across the Stars (Augmented Remaster)", videoId: "3QyrEcpPivU" },
    { title: "Cryptopiano - Celestial Waves (Augmented Remaster)", videoId: "RkhiOQtwu9I" },
    { title: "Cryptopiano - Black Matter (Augmented Remaster)", videoId: "ubKdKWrEU5k" },
    { title: "Cryptopiano - Collision in the Void (Augmented Remaster)", videoId: "hmZylpOrhY4" },
    { title: "Cryptopiano - Infinity Secrets", videoId: "F7dePAm2o4w" },
    { title: "Cryptopiano - Life's Polyphony", videoId: "TdS9GOEOhGI" },
    { title: "Cryptopiano - Heart Beats Like Drum Beats", videoId: "vKWBVX6xQTE" },
    { title: "Cryptopiano - Life Energy", videoId: "h0XONoQPGXg" },
    { title: "Cryptopiano - When Reality Bends", videoId: "56sZqYxcWus" },
    { title: "Cryptopiano - Music Magnetic", videoId: "9JupF3MnDC4" },
    { title: "Cryptopiano - Sounds That Keep Me Alive", videoId: "ON_vrbwRclk" },
    { title: "Cryptopiano - Peaceful Existence", videoId: "i9uURXrWBKg" },
    { title: "Cryptopiano - Overdrive Bliss", videoId: "JEEvyHJxu38" },
    { title: "Cryptopiano - Apex Dream", videoId: "mmGeQT8xxNQ" },
    { title: "Cryptopiano - Quantum Veil", videoId: "iTFfWEMi0aI" },
    { title: "Cryptopiano - Paradox", videoId: "X55TEtQkhxA" },
    { title: "Cryptopiano - Invisible Walls", videoId: "GTBSDKVg2Y8" },
    { title: "Cryptopiano - Shaken Grounds", videoId: "90VJu-BRXf8" },
    { title: "Cryptopiano - Ancient Echoes", videoId: "wnzSuSvB6Kw" },
    { title: "Cryptopiano - Sixth Sense", videoId: "QUwCA7tzPOo" },
    { title: "Cryptopiano - Open Blue Skies", videoId: "g4iYzaxFe0k" },
    { title: "Cryptopiano - Diamond Ship (Remastered)", videoId: "7SQxU3gdxu0" },
    { title: "Cryptopiano - Learning to Breathe Again", videoId: "-73pvo8oUoo" },
    { title: "Cryptopiano - Voyager's Dream", videoId: "-yfm1M9UNgM" },
    { title: "Cryptopiano - Purple Heart (Remastered)", videoId: "CIdvokHs78w" },
    { title: "Cryptopiano - Unicorn in My Botanical Garden (Remastered)", videoId: "ULPhnb3ZgpA" },
    { title: "Cryptopiano - Dream or Reality (Remastered)", videoId: "pfarBY3WI6Y" },
    { title: "Cryptopiano - Cosmic Cadence (Remastered)", videoId: "iOYWuxShYnY" },
    { title: "Cryptopiano - Magnetic Roundabout", videoId: "E3mAG2STPjc" },
    { title: "Cryptopiano - Magnetic Dreams (Remastered)", videoId: "CSb3CyPTHvE" },
    { title: "Cryptopiano - Rubato Baby", videoId: "jZLaZh5ma2o" },
    { title: "Cryptopiano - Forgive the Past", videoId: "z6D5Fz2Y2JY" },
    { title: "Cryptopiano - Dimensions Beyond", videoId: "KmVvP6kts8I" },
    { title: "Cryptopiano - Magical Escape", videoId: "9UVzx1Z1Vi8" },
    { title: "Cryptopiano - Too Little Too Late", videoId: "oORCAc0dKS8" },
    { title: "Cryptopiano - Starfish Seal", videoId: "CywGVhI8iMk" },
    { title: "Cryptopiano - Touched by the Creation", videoId: "qkI663pIYxs" },
    { title: "Cryptopiano - Digital Soul", videoId: "r2DL3sHGiT8" },
    { title: "Cryptopiano - Syncopated Life", videoId: "hmAF-rrD5FQ" },
    { title: "Cryptopiano - Luminous Curiosity", videoId: "IdSatP6e_Bk" },
    { title: "Cryptopiano - Spiritual Rebirth", videoId: "W2yXqPd2ldE" },
    { title: "Cryptopiano - Dimensions Beyond Exposition", videoId: "DcI0Bh6_qNo" },
    { title: "Cryptopiano - Revenant", videoId: "k7WrJuXNLQk" },
    { title: "Cryptopiano - Lost in the Echoes (Remastered)", videoId: "2qrNkv4bYF0" },
    { title: "Cryptopiano - When Everything Fades Away (Remastered)", videoId: "IeiEaRb7uCw" },
    { title: "Cryptopiano - The Real Friendships (Remastered)", videoId: "lhFwpzZ66vI" },
    { title: "Cryptopiano - Wandering Blues (Remastered)", videoId: "e2MWvGbiGgg" },
    { title: "Cryptopiano - The Life Leads the Way (Remastered)", videoId: "ipmKyaGql7I" },
    { title: "Cryptopiano - Day One (Remastered)", videoId: "73jpRAN68QM" },
    { title: "Cryptopiano - The Day I Crossed the Ocean (Remastered)", videoId: "JiTtu26K5h0" },
    { title: "Cryptopiano - Loving Life", videoId: "0wHuUv8ziiY" },
    { title: "Cryptopiano - Dreamless Echoes", videoId: "hSkGzvQD_DE" },
    { title: "Cryptopiano - Finding Light", videoId: "diMZ1wfN4_c" },
    { title: "Cryptopiano - Angels", videoId: "ZcqNS6V2gdk" },
    { title: "Cryptopiano - Stars Above", videoId: "4BJg983WaDM" },
    { title: "Cryptopiano - Adria Loves You Always", videoId: "7xxPn-j7Pqs" },
    { title: "Cryptopiano - Disappearing from This Time Plane", videoId: "ZgYrGfz3KZM" },
    { title: "Cryptopiano - Transcending Soul Chains", videoId: "bwaPvEROiuw" },
    { title: "Cryptopiano - Transcending Soul Chains (Short)", videoId: "SdLWACRYBqs" },
    { title: "Cryptopiano - Drifting Faces in the Mist", videoId: "fXkFZA95GfY" },
    { title: "Cryptopiano - Waves of You", videoId: "o24LJdTyK8w" },
    { title: "Cryptopiano - Longing", videoId: "4Krkw9pL1AQ" },
    { title: "Cryptopiano - When Waves Weep", videoId: "6fOE3veSwhg" },
    { title: "Cryptopiano - Locked Looks (Remastered)", videoId: "VTw6iArUM6k" },
    { title: "Cryptopiano - Let's Dare Together", videoId: "OYvanNdA5qU" },
    { title: "Cryptopiano - An Imagination in the Sand", videoId: "HgN7PBspPVc" },
    { title: "Cryptopiano - Easy Music Story", videoId: "Nc80p8t_KUw" },
    { title: "Cryptopiano - Gray Day Today", videoId: "3gjIjar3Bto" },
    { title: "Cryptopiano - Mantra", videoId: "ygSr0q6E-nY" },
    { title: "Cryptopiano - Beauty All Around", videoId: "FqErOp7JhUU" },
    { title: "Cryptopiano - Paradise of Peace", videoId: "kXo9alqtu6I" },
    { title: "Cryptopiano - Celestial Secrets", videoId: "47-F_VasoPo" },
    { title: "Cryptopiano - Lost in Magic", videoId: "1fyUDG4HWVY" },
    { title: "Cryptopiano - Drifting in the Rainbow Galaxy", videoId: "p40X4jwfkJY" },
    { title: "Cryptopiano - Cosmic Voyage", videoId: "PDMxP86Sfw8" },
    { title: "Cryptopiano - Rainbow's Glow", videoId: "eH0NRbju2oA" },
    { title: "Cryptopiano - Celestial Light", videoId: "Ap3cMgg8824" },
    { title: "Cryptopiano - Magic Suitcase", videoId: "PSgDzXmWGy4" },
    { title: "Cryptopiano - Serenade of the Desolate Stars", videoId: "vGyGsA7_jrA" },
    { title: "Cryptopiano - Mysteries of the Golden Planet", videoId: "gAzwDs-JTYk" },
    { title: "Cryptopiano - Golden Planet", videoId: "hl2CNwcyykY" },
    { title: "Cryptopiano - Astral Odyssey", videoId: "Og68Fc7ULf8" },
    { title: "Cryptopiano - Boy Oh Boy", videoId: "XxTfEI_ZRA8" },
    { title: "Cryptopiano - Forever Young", videoId: "AgX9Z7E1NVU" },
    { title: "Cryptopiano - Irish Coffee Punk", videoId: "TFToR6ZFwjE" },
    { title: "Cryptopiano - Hopes for a New Year", videoId: "172CuY4kNa0" },
    { title: "Cryptopiano - Midnight Jam", videoId: "M6-fNWJJ000" },
    { title: "Cryptopiano - Eternal Velvet II", videoId: "BZ9OR0QQREs" },
    { title: "Cryptopiano - Toast to Dreams", videoId: "RmbeKSNmMDA" },
    { title: "Cryptopiano - Waikiki Stroll", videoId: "lBRYivpCsYs" },
    { title: "Cryptopiano - Edge of the Year", videoId: "s9rBNR3bJhc" },
    { title: "Cryptopiano - Caught in the Whirlwind", videoId: "w5edVl--cS4" },
    { title: "Cryptopiano - Sunset Road", videoId: "bcF6zrhgYUc" },
    { title: "Cryptopiano - Highways Call Our Names", videoId: "wCfoCvilv-s" },
    { title: "Cryptopiano - Shoulder to Cry On", videoId: "Y9OLzDfWcfM" },
    { title: "Cryptopiano - Heavenly Dreaming", videoId: "-vSzi_cLcDk" },
    { title: "Cryptopiano - Swaying With the Wind", videoId: "OhRGUt1Lx0Q" },
    { title: "Cryptopiano - Holly Jolly Nights", videoId: "-ccAXuwhG58" },
    { title: "Cryptopiano - A  Frosty Serenade", videoId: "vFNJfGE-gvk" },
    { title: "Cryptopiano - A Silent Snowfall", videoId: "uJpGe4G0WWI" },
    { title: "Cryptopiano - Chasing Cities Around the World", videoId: "7SdQk8qaxWA" },
    { title: "Cryptopiano - Soulmates in Dreams", videoId: "ls5Miku1Ogw" },
    { title: "Cryptopiano - Midnight Kiss", videoId: "vwXRKZpsbiU" },
    { title: "Cryptopiano - Sweet Memories", videoId: "cu8w-aYd_Ls" },
    { title: "Cryptopiano - Eternal Velvet Love", videoId: "jC27IBm5hg8" },
    { title: "Cryptopiano - Vibrant Life", videoId: "yAd6q2Bx-Sw" },
    { title: "Cryptopiano - Dream Island", videoId: "gCcHAjXdos0" },
    { title: "Cryptopiano - Dream, Dream, Dream", videoId: "QmXPEvauHaM" },
    { title: "Cryptopiano - Hope for Tomorrow", videoId: "FQoCVUb9uPA" },
    { title: "Cryptopiano - Time's Lost", videoId: "nB_DgZeXogE" },
    { title: "Cryptopiano - Faded Choices", videoId: "0vcLSzITXeA" },
    { title: "Cryptopiano - Soul's Rebellion", videoId: "5AbZfHq5Fp0" },
    { title: "Cryptopiano - Home Sweet Home", videoId: "nm5y1RgTvvg" },
    { title: "Cryptopiano - Convergence", videoId: "PVwOARIJzP0" },
    { title: "Cryptopiano - Galactic Drift", videoId: "xtAAaJIar7k" },
    { title: "Cryptopiano - Crying Star", videoId: "sp2qF5WA92E" },
    { title: "Cryptopiano - Cosmic Love", videoId: "mBy7V78PPxw" },
    { title: "Cryptopiano - Earth Bound", videoId: "rjlhvZpLIv8" },
    { title: "Cryptopiano - Bringing Them Back", videoId: "eevenJiPTY4" },
    { title: "Cryptopiano - The Sky of 2140", videoId: "EiAdrZSu4kM" },
    { title: "Cryptopiano - Intergalactic Stories", videoId: "AL8E5t82HEs" },
    { title: "Cryptopiano - Meeting My Future Self", videoId: "OrUDK21QpWU" },
    { title: "Cryptopiano - Infinite Rainbow Love", videoId: "5uPISRGLvAI" },
    { title: "Cryptopiano - Ghosts in the Cosmos", videoId: "ZklgWFQpTPY" },
    { title: "Cryptopiano - Endless Echoes", videoId: "xmZCIIiBb-c" },
    { title: "Cryptopiano - Unknown Species", videoId: "P9We30wlDj4" },
    { title: "Cryptopiano - Golden Planet", videoId: "UzNKOuRn-aI" },
    { title: "Cryptopiano - Cosmic Escapades", videoId: "DR6nanIVsVA" },
    { title: "Cryptopiano - Diamond Spaceship", videoId: "B4u5fch1Gw4" },
    { title: "Cryptopiano - Rainbow Cosmos", videoId: "USZouwzYeKI" },
    { title: "Cryptopiano - Entangled Hearts", videoId: "iPRaP7W-LP8" },
    { title: "Cryptopiano - Time Travel Twist", videoId: "p54txPAzlwE" },
    { title: "Cryptopiano - Unknown Wormhole", videoId: "cSdhc1JCQ74" },
    { title: "Cryptopiano - Quantum Mirror", videoId: "lqRun84dIOY" },
    { title: "Cryptopiano - Blackhole Serenade", videoId: "ILyYiH93DC0" },
    { title: "Cryptopiano - Centrifuge Dream", videoId: "DxhALLzFgeY" },
    { title: "Cryptopiano - Secret Stargate", videoId: "GevXhS_YttA" },
    { title: "Cryptopiano - Magical Space Tablet", videoId: "7X-8NwHDQyo" },
    { title: "Cryptopiano - Dreams in Stasis", videoId: "jylI-GkJmOE" },
    { title: "Cryptopiano - Purple Space Suit", videoId: "tp4dMGcmd88" },
    { title: "Cryptopiano - Imagination Spell", videoId: "vjKQcEBN3tE" },
    { title: "Cryptopiano - Nebula Dreams", videoId: "x341eF7KQn8" },
    { title: "Cryptopiano - Perpetual Layers", videoId: "SA8ppEmyj1s" },
    { title: "Cryptopiano - Weightless Space Float", videoId: "Jhep0xxp5rA" },
    { title: "Cryptopiano - Turn Back Time", videoId: "zKy_d-rgRB4" },
    { title: "Cryptopiano - Timeless Flow", videoId: "CeTBtB0A1NM" },
    { title: "Cryptopiano - I'll Bend the Time", videoId: "5yXQXeMWSQ8" },
    { title: "Cryptopiano - Little Older but Younger at Heart", videoId: "K3BmZOtQdcg" },
    { title: "Cryptopiano - We Are Still Close Can't You Feel", videoId: "FJg8YJAE_6M" },
    { title: "Cryptopiano - The Sound of Your Voice", videoId: "ag1_H3T8Qlw" },
    { title: "Cryptopiano - Endless Little Games", videoId: "4lOIQ-b5pqU" },
    { title: "Cryptopiano - Electric Shadows", videoId: "ccr6q7-km_M" },
    { title: "Cryptopiano - Fork in the Road", videoId: "DxLTnKuUMxY" },
    { title: "Cryptopiano - Her Smile", videoId: "YvJD39zDKZI" },
    { title: "Cryptopiano - Untouchable Visions", videoId: "QgA-RCbA2EI" },
    { title: "Cryptopiano - Sky Dance", videoId: "sENj6dU2twQ" },
    { title: "Cryptopiano - Burning Glow", videoId: "Vd_BDdaIXdg" },
    { title: "Cryptopiano - Colorful Mirage", videoId: "cKR4aAM8YQo" },
    { title: "Cryptopiano - Dreamers Are Forever", videoId: "OYjWx0n5aD0" },
    { title: "Cryptopiano - Magnetic Attraction", videoId: "D0Gh6KXzzWI" },
    { title: "Cryptopiano - Locked Looks", videoId: "72w4re8BRjs" },
    { title: "Cryptopiano - Ocean's Edge", videoId: "3ceXd74_bpY" },
    { title: "Cryptopiano - Life's Embrace", videoId: "wop_S8nSNOk" },
    { title: "Cryptopiano - Ocean Horizon", videoId: "s6eHX0e_DmM" },
    { title: "Cryptopiano - Sunshine Smiles", videoId: "KRVK8oh29eY" },
    { title: "Cryptopiano - Bliss of Morning", videoId: "jKA7lS9GKLw" },
    { title: "Cryptopiano - Ocean Waves Arabesque", videoId: "F4d77xF_qlc" },
    { title: "Cryptopiano - Dolphins Dance", videoId: "ZBwWNU7nAzg" },
    { title: "Cryptopiano - Hidden Island", videoId: "Y-ErOwJW2iw" },
    { title: "Cryptopiano - Mystic Waves of the Undead Sea", videoId: "Cb-U_RYMbxE" },
    { title: "Cryptopiano - Hidden Treasure", videoId: "DPJEFK5nT_U" },
    { title: "Cryptopiano - Mystic Pirate's Tale", videoId: "6-yfqlKpG0M" },
    { title: "Cryptopiano - Mystical Underwater Cave", videoId: "qG1HOj8fl8U" },
    { title: "Cryptopiano - Ocean Fairy Tale", videoId: "-ase_jmqB_c" },
    { title: "Cryptopiano - Mermaid of Love", videoId: "ltP5pAKOpXk" },
    { title: "Cryptopiano - Ocean's Where My Soul Floats", videoId: "isYylVzL6es" },
    { title: "Cryptopiano - Ghosts of the Deep", videoId: "YHT-HFrCzog" },
    { title: "Cryptopiano - Wonders of the Ocean", videoId: "JtI4i7i7iM0" },
    { title: "Cryptopiano - Aquarius Lady of the Sea", videoId: "8ColUFXbAWw" },
    { title: "Cryptopiano - Ocean's Forgotten Stories", videoId: "yxj3Yt4Cp8w" },
    { title: "Cryptopiano - Ocean's Rhapsody", videoId: "IiNma_yzczs" },
    { title: "Cryptopiano - Endless Blue", videoId: "lOHzWEoAEVM" },
    { title: "Cryptopiano - Whispers of Love", videoId: "UpnHWCAfiUU" },
    { title: "Cryptopiano - When the Curtains Fall", videoId: "VVK0GPTPYIo" },
    { title: "Cryptopiano - Thank You for Good Days", videoId: "DQ09lieLkFs" },
    { title: "Cryptopiano - End of an Era", videoId: "2MRYKVrwX3k" },
    { title: "Cryptopiano - Trade Winds Blues", videoId: "HE4sF4lRzn8" },
    { title: "Cryptopiano - Meet You On the Other Side", videoId: "cTFkOp7OG-A" },
    { title: "Cryptopiano - Jazzy Day", videoId: "bW0yMcrhgSg" },
    { title: "Cryptopiano - Retrospective Blues", videoId: "H2-fELsWhFo" },
    { title: "Cryptopiano - Waikiki Day", videoId: "r7IINwPoov0" },
    { title: "Cryptopiano - Sunshine Every Day", videoId: "xlkIxQEcQqQ" },
    { title: "Cryptopiano - Surf Time Breeze", videoId: "vPfW9GsO3qY" },
    { title: "Cryptopiano - Sail to the Sea of Dreams", videoId: "IUAqi6egixE" },
    { title: "Cryptopiano - Seven Cities, Seven Lives", videoId: "e_tDZHlqZEI" },
    { title: "Cryptopiano - New Dawn Rising 2024", videoId: "-oSNIsX7dQY" },
    { title: "Cryptopiano - Let's Dance Till Morning", videoId: "QldUn8GWetM" },
    { title: "Cryptopiano - Sail Away", videoId: "gngRxGkX8ao" },
    { title: "Cryptopiano - Swaying Palms", videoId: "EANZey8w0Lg" },
    { title: "Cryptopiano - Island Night", videoId: "KG7hFXXIK2U" },
    { title: "Cryptopiano - Hawaiian Dreams", videoId: "lHUQ51jkmJ8" },
    { title: "Cryptopiano - Aloha Kūpaʻa", videoId: "IgosyN_0LA0" },
    { title: "Cryptopiano - Swim to the Sun", videoId: "dlsU5okxQyc" },
    { title: "Cryptopiano - Don't Leave", videoId: "Pe_pzrn-CFI" },
    { title: "Cryptopiano - In the Deep Where the Whales Cry", videoId: "11TZIbPiCgA" },
    { title: "Cryptopiano - Shaka Spirit", videoId: "DYC2bbCpzts" },
    { title: "Cryptopiano - Ocean is My Heart", videoId: "e-8DrLm4JR0" },
    { title: "Cryptopiano - Breath of Existence", videoId: "2hrAns0ry9A" },
    { title: "Cryptopiano - Aquarius", videoId: "IctDd-GEIFk" },
    { title: "Cryptopiano - Starlit Dreams", videoId: "4FkXsU4gO1w" },
    { title: "Cryptopiano - Water's Lullaby", videoId: "XVPshC5oSO0" },
    { title: "Cryptopiano - Days Fly", videoId: "qFGHDjvJRvE" },
    { title: "Cryptopiano - Wake Up You", videoId: "uj8UM5ZH11o" },
    { title: "Cryptopiano - Ascending Soul Melody", videoId: "kpuNEOjrlzs" },
    { title: "Cryptopiano - Premonitions", videoId: "Y92XZdJmSx0" },
    { title: "Cryptopiano - Let the Seed Grow", videoId: "1dC0vvsalyc" },
    { title: "Cryptopiano - Golden Leaves", videoId: "20uUyynWR2g" },
    { title: "Cryptopiano - Quiet Mind", videoId: "uI2cBYAxgzw" },
    { title: "Cryptopiano - Peaceful Mind", videoId: "WrTqkMFNOuQ" },
    { title: "Cryptopiano - Inner Peace", videoId: "XV1f91Egi-k" },
    { title: "Cryptopiano - Breathe In Peace", videoId: "uU-f-VHSRc4" },
    { title: "Cryptopiano - Serene Tomorrow", videoId: "U4RoU-FB4M4" },
    { title: "Cryptopiano - Drops of Water on My Face", videoId: "YpU6uyTJduY" },
    { title: "Cryptopiano - Waterfalls", videoId: "7fHxOpEbLMA" },
    { title: "Cryptopiano - Until We Meet Again", videoId: "i7CBc1yjcco" },
    { title: "Cryptopiano - Remember When", videoId: "yZ8nEhNZNuo" },
    { title: "Cryptopiano - Pink Sand Dreams", videoId: "QWnEN9Orjy4" },
    { title: "Cryptopiano - Close My Eyes", videoId: "gHQ9nMgR82k" },
    { title: "Cryptopiano - I Will Miss You Always", videoId: "ktK4AtqDMJw" },
    { title: "Cryptopiano - Everlasting Love", videoId: "l3wB9FuH-f8" },
    { title: "Cryptopiano - Echoes of Yesterday", videoId: "UCohrPNb5gE" },
    { title: "Cryptopiano - End or Dawn", videoId: "Vxlr1t8vBn8" },
    { title: "Cryptopiano - Time Is Slipping", videoId: "kJNt3ZoE0lk" },
    { title: "Cryptopiano - Live for Now", videoId: "E7QNbgSHiNo" },
    { title: "Cryptopiano - Silent Storm", videoId: "sW_iFeOlDPI" },
    { title: "Cryptopiano - Parallel Universe", videoId: "vsM9_8A_3PQ" },
    { title: "Cryptopiano - Prophetic Mind", videoId: "SAVAev77Vbc" },
    { title: "Cryptopiano - Visionary Darkness", videoId: "1cnubgYBhWg" },
    { title: "Cryptopiano - The Seer's Whisper", videoId: "9xoo76oWasM" },
    { title: "Cryptopiano - Prophetic Eyes", videoId: "cREmPnV6o0U" },
    { title: "Cryptopiano - Beneath the Same Stars", videoId: "ukpKvxhE5Eg" },
    { title: "Cryptopiano - Parallel Reflections", videoId: "noHgWp1bfdE" },
    { title: "Cryptopiano - Peaceful Echoes", videoId: "NEEGB7jprMA" },
    { title: "Cryptopiano - Inflation Rise", videoId: "Ar8E56IPZZk" },
    { title: "Cryptopiano - Hidden Mysteries", videoId: "R9nk_t076pg" },
    { title: "Cryptopiano - Wandering Soul", videoId: "FhQb1pa1ZUc" },
    { title: "Cryptopiano - Desolation II", videoId: "kbZertQCSAE" },
    { title: "Cryptopiano - Empty Streets", videoId: "Q3DPiZJ1tHM" },
    { title: "Cryptopiano - Lost in the Maze II", videoId: "iRoUoWwH_Wc" },
    { title: "Cryptopiano - Defensive Stance II", videoId: "k5lSwSS7XvQ" },
    { title: "Cryptopiano - Lost in Shadows", videoId: "614LMiqbFPY" },
    { title: "Cryptopiano - Breath and Sigh", videoId: "8bA_Q4ZdfVs" },
    { title: "Cryptopiano - Whispers in Shadows", videoId: "hTAbxYL7poI" },
    { title: "Cryptopiano - Moonlight Guides Our Way 2024", videoId: "rQ8oMOZJYK8" },
    { title: "Cryptopiano - Edge of Reality", videoId: "cGP2QgjjiLI" },
    { title: "Cryptopiano - Finale", videoId: "oQ4MD9w95CU" },
    { title: "Cryptopiano - Life's Puzzle", videoId: "TuqF-KPcjyA" },
    { title: "Cryptopiano - Days, Months, Years, Decades I Remember", videoId: "fa-U-6lgbGA" },
    { title: "Cryptopiano - Infinite Roads", videoId: "J7RxVbl1fNk" },
    { title: "Cryptopiano - Life's Choices", videoId: "1ikuJqtS_xo" },
    { title: "Cryptopiano - Diabolical Mind", videoId: "CEmvHhXvTI0" },
    { title: "Cryptopiano - Question Everything", videoId: "sttYo9KE8iw" },
    { title: "Cryptopiano - Leaving the Sorrows", videoId: "w9smVAToxjw" },
    { title: "Cryptopiano - Lost in Soul", videoId: "_ey77_eP8YI" },
    { title: "Cryptopiano - Infinity Calls Us", videoId: "4fnyvFbt91c" },
    { title: "Cryptopiano - Unseen Paths", videoId: "CZT4nY9DujM" },
    { title: "Cryptopiano - End of the Road", videoId: "w7yM1OSg_pc" },
    { title: "Cryptopiano - Beautiful Happy Minds II", videoId: "0f6h9E1-NKM" },
    { title: "Cryptopiano - Far Away Tune", videoId: "5LI631FuQjM" },
    { title: "Cryptopiano - Songs We Sang in the Car", videoId: "DTNca09hBIE" },
    { title: "Cryptopiano - My Little Rabbit", videoId: "-PSfwbgcbXg" },
    { title: "Cryptopiano - Songs We Sang", videoId: "ObuRe63kLoI" },
    { title: "Cryptopiano - Daddy Lift Me Up", videoId: "oP20Mwka-Y0" },
    { title: "Cryptopiano - Family is Forever", videoId: "rMGyCyXhQiU" },
    { title: "Cryptopiano - Ride My Bird", videoId: "-nUZNLezQO0" },
    { title: "Cryptopiano - Forget About Troubles", videoId: "JHg2h4t1zpk" },
    { title: "Cryptopiano - Every Day A Beach Day", videoId: "2uByOKSu5Pc" },
    { title: "Cryptopiano - The Magic Coin", videoId: "HSXYsgY4JxM" },
    { title: "Cryptopiano - Chains of Thought", videoId: "q7YpUZYFav0" },
    { title: "Cryptopiano - Friendly Smile Saves the Day", videoId: "y_CYgjX5WDo" },
    { title: "Cryptopiano - Dance With Me", videoId: "IYSKK9LYoDE" },
    { title: "Cryptopiano - Think Light Stay Bright", videoId: "7YXoNAEsbnc" },
    { title: "Cryptopiano - My Audible Thoughts", videoId: "6P2IcDtv3h0" },
    { title: "Cryptopiano - Beautiful Happy Minds", videoId: "mdgIwH5E8gU" },
    { title: "Cryptopiano - Echoes of Joy", videoId: "VYGDwzzgaPU" },
    { title: "Cryptopiano - Piece of Mind", videoId: "wF41sKnYmdM" },
    { title: "Cryptopiano - Inner Peace", videoId: "YBmQWgUQtA4" },
    { title: "Cryptopiano - Through the Mist", videoId: "i59_JO2ySV4" },
    { title: "Cryptopiano - Timbres of Rainbow", videoId: "FmKTy0sNwJs" },
    { title: "Cryptopiano - Ivory  Dance", videoId: "iVHElRQEU_s" },
    { title: "Cryptopiano - Tree house", videoId: "zOw7R-Qp86I" },
    { title: "Cryptopiano - Echoes on Ivory", videoId: "tq36YY4hlB0" },
    { title: "Cryptopiano - Echoes of Today", videoId: "k_l1zirzzIk" },
    { title: "Cryptopiano - Waves of Eternity", videoId: "s2beDG04En8" },
    { title: "Cryptopiano - Bit By Bit", videoId: "3-hccnf-TWw" },
    { title: "Cryptopiano - Life's Wave", videoId: "JYxtwRGEN-M" },
    { title: "Cryptopiano - Can You See Me", videoId: "PISgLWs1QQw" },
    { title: "Cryptopiano - Echoes in the Crowd", videoId: "SNRyyPsLmwo" },
    { title: "Cryptopiano - Doomed Names", videoId: "Ws1p-GKO9yI" },
    { title: "Cryptopiano - Over the Ocean I Fly", videoId: "sZFTp0zE1xA" },
    { title: "Cryptopiano - Dreamwaves", videoId: "1Rvw6ZF_rCE" },
    { title: "Cryptopiano - Hide From the World", videoId: "FIU1-vWqGvU" },
    { title: "Cryptopiano - High Frequency", videoId: "MfqEkMedb6g" },
    { title: "Cryptopiano - Right Now", videoId: "DfqYDVic4dE" },
    { title: "Cryptopiano - Shadows and Secrets", videoId: "Ms8i0xXAqIk" },
    { title: "Cryptopiano - Four Years Gone", videoId: "pv0OKgqDbuM" },
    { title: "Cryptopiano - Behind the Curtain", videoId: "mIxKQSlfVTY" },
    { title: "Cryptopiano - Day by Day", videoId: "ktu2zIxz3XY" },
    { title: "Cryptopiano - Losing My Ground", videoId: "kyEGqMKJLLY" },
    { title: "Cryptopiano - Cosmic Whispers", videoId: "Bzwc05GGWB4" },
    { title: "Cryptopiano - Galaxies Turning", videoId: "MK7luSWWO8k" },
    { title: "Cryptopiano - Fringe in Space", videoId: "5e9VH6EFM3M" },
    { title: "Cryptopiano - Strange Planet", videoId: "Ie9dxtv48jY" },
    { title: "Cryptopiano - Two Minutes Left", videoId: "9YTZ5QNNu3A" },
    { title: "Cryptopiano - Hiding On a Strange Planet", videoId: "3iltSitkKB0" },
    { title: "Cryptopiano - Alien Attack", videoId: "Pa2IYQhDRjo" },
    { title: "Cryptopiano - Alien Chase", videoId: "F0YCFOZlte4" },
    { title: "Cryptopiano - Across the Stars", videoId: "Xh2LraZaogo" },
    { title: "Cryptopiano - Celestial Waves", videoId: "vxTSZiRpO9o" },
    { title: "Cryptopiano - Black Matter", videoId: "iLvKBk3899E" },
    { title: "Cryptopiano - Collision in the Void", videoId: "9ol04Alm_7o" },
    { title: "Cryptopiano - Gold Planet", videoId: "kmlOYGItAj4" },
    { title: "Cryptopiano - Diamond Ship", videoId: "KsJ6hQHYhGY" },
    { title: "Cryptopiano - Cosmic Shell", videoId: "H6MH8x8tLNw" },
    { title: "Cryptopiano - Cosmic Dust", videoId: "NySM4AscoEs" },
    { title: "Cryptopiano - Voyager's Dream", videoId: "UprQYqysY-s" },
    { title: "Cryptopiano - Purple Heart", videoId: "4_p1zdzCyCo" },
    { title: "Cryptopiano - Heart of the Universe", videoId: "DdnBL-RFUvw" },
    { title: "Cryptopiano - Octagon Palace", videoId: "NJP630UwXJQ" },
    { title: "Cryptopiano - Unicorn in My Botanical Garden", videoId: "GKm9qoDJfgA" },
    { title: "Cryptopiano - Floating City", videoId: "mJpIfaN8Ywg" },
    { title: "Cryptopiano - My Flying Car", videoId: "yY9NiGr0LC8" },
    { title: "Cryptopiano - Cosmic Eye", videoId: "6E7qiKg7M28" },
    { title: "Cryptopiano - Weightless Kiss", videoId: "KLbGtJrLeaY" },
    { title: "Cryptopiano - Rainbow Galaxy", videoId: "UHclNbOSJQ4" },
    { title: "Cryptopiano - Dream or Reality", videoId: "MlNrk-e99TE" },
    { title: "Cryptopiano - Forever Echoes", videoId: "q9tFrMFali4" },
    { title: "Cryptopiano - Nothing Ever Dies", videoId: "HC7S8qEJbeg" },
    { title: "Cryptopiano - Cosmic Cadence", videoId: "FJx1aXTmR9Q" },
    { title: "Cryptopiano - Lost in the Echoes", videoId: "z4sNBCoZDO8" },
    { title: "Cryptopiano - When Everything Fades Away", videoId: "KJoOdoxE-Q8" },
    { title: "Cryptopiano - The Real Friendships", videoId: "XwFd7ZYlRmI" },
    { title: "Cryptopiano - Wandering Blues", videoId: "XdnELkQULhQ" },
    { title: "Cryptopiano - Many Cities Many Faces", videoId: "6Llfpo9_UDE" },
    { title: "Cryptopiano - Grandma's Ring", videoId: "psxFMQjq90Y" },
    { title: "Cryptopiano - Grandma's Hand", videoId: "gVw98F3adoU" },
    { title: "Cryptopiano - The Life Leads the Way", videoId: "b54T4X365e8" },
    { title: "Cryptopiano - Day One", videoId: "azbdREjsRxs" },
    { title: "Cryptopiano - The Day I Crossed the Ocean", videoId: "77glIAOhT3Y" },
    { title: "Cryptopiano - Law of Attraction", videoId: "_zA-HMshEI8" },
    { title: "Cryptopiano - Magnetic Dreams", videoId: "SQVOA4E1y8o" },
    { title: "Cryptopiano - Aura of Light", videoId: "HVs-jRySP_Q" },
    { title: "Cryptopiano - The Day I'll Never Forget", videoId: "iGIrMq95BIA" },
    { title: "Cryptopiano - Time Can't Erase Us", videoId: "2KOym2x041g" }
];
